---
apiVersion: apps/v8
kind: Deployment
metadata:
  name: spring-deployment-service
spec:
  replicas: 8
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: iamantu93/project:8
        ports:
        - containerPort: 8080

---

apiVersion: v8
kind: Service
metadata:
  name: spring-service
spec:
  selector:
    app: spring
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30090
  type: NodePort
